services:
  web:
    build: .
    expose:
      - 8000
    volumes:
      - .:/app
      - db_data:/app/news.db
    environment:
      - DATABASE_URL=sqlite:///./news.db
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - news_network
  
  frontend:
    build: ./frontend
    expose:
      - 8501
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://web:8000
    depends_on:
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - news_network
    labels:
      # Essential WebSocket support for Traefik - will be merged with PaaS labels
      - "traefik.http.middlewares.streamlit-ws.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.streamlit-ws.headers.customrequestheaders.X-Forwarded-Host=${TRAEFIK_HOST:-localhost}"
      - "traefik.http.middlewares.streamlit-ws.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.middlewares.streamlit-ws.headers.customrequestheaders.Upgrade=websocket"
      # Add this to both router definitions (will be appended to PaaS middleware chains)
      - "traefik.http.routers.sqr-project-dev-frcqok-100-websecure.middlewares=streamlit-ws@docker"

networks:
  news_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  
  