services:
  web:
    build: .
    ports:
      - "${PORT:-3671}:8000"
    volumes:
      - .:/app
      - db_data:/app/news.db
    environment:
      - DATABASE_URL=sqlite:///./news.db
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - news_network
  
  frontend:
    build: ./frontend
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://web:8000
    depends_on:
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - news_network

networks:
  news_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  
  