services:
  web:
    build: .
    expose:
      - 8000
    volumes:
      - .:/app
      - db_data:/app/news.db
    environment:
      - DATABASE_URL=sqlite:///./news.db
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - news_network
  
  frontend:
    build: ./frontend
    expose:
      - 8501
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://web:8000
      - STREAMLIT_SERVER_ENABLE_CORS=true
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_SERVER_BASE_URL_PATH=
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    depends_on:
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - news_network
    labels:
      # Essential routing configuration
      - "traefik.enable=true"
      - "traefik.http.services.streamlit.loadbalancer.server.port=8501"
      - "traefik.http.routers.sqr-project-dev-frcqok-100-web.rule=Host(`sqr-project-dev-frcqok-ab42d2-74-179-83-105.traefik.me`)"
      - "traefik.http.routers.sqr-project-dev-frcqok-100-web.service=streamlit"
      
      # Essential WebSocket support for HTTP Traefik
      - "traefik.http.middlewares.streamlit-ws.headers.customrequestheaders.X-Forwarded-Proto=http"
      - "traefik.http.middlewares.streamlit-ws.headers.customrequestheaders.X-Forwarded-Host=sqr-project-dev-frcqok-ab42d2-74-179-83-105.traefik.me"
      - "traefik.http.middlewares.streamlit-ws.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.middlewares.streamlit-ws.headers.customrequestheaders.Upgrade=websocket"
      
      # Apply middleware to the HTTP router
      - "traefik.http.routers.sqr-project-dev-frcqok-100-web.middlewares=streamlit-ws@docker"

networks:
  news_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  
  