[server]
enableCORS = true
enableXsrfProtection = false
headless = true
enableWebsocketCompression = false
maxUploadSize = 50
maxMessageSize = 200
# Add origin to specify your domain
allowedOrigins = ["*"]

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501 