[server]
enableCORS = true
enableXsrfProtection = false
headless = true
enableWebsocketCompression = false
maxUploadSize = 50
maxMessageSize = 200
# Force HTTP protocol
useSSL = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501 